// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type File struct {
	Hash       string
	Filename   string
	Extension  string
	Size       int64
	Password   sql.NullString
	UploadedAt time.Time
	ExpiresAt  sql.NullTime
}

type Paste struct {
	Hash       string
	Filename   string
	Size       int64
	Language   sql.NullString
	Password   sql.NullString
	UploadedAt time.Time
	ExpiresAt  sql.NullTime
}

type Token struct {
	Token     string
	CreatedAt time.Time
}
